### PR TITLE
Change ijson version in setup.py install_requires to be 2.3

### PR DESCRIPTION
**Pull request by IdanHaim**
ijson lib has been changed, supported until version 2.3.

### CODE REVIEW

**Review by ayende — APPROVED** [review]

**Comment by TobiasGoerke** [comment]
Fixing the ijson version like this causes ravendb to conflict with other packages, especially newer ones.. 
Is there any way the ijson can be updated?

**Comment by poissoncorp** [comment]
@TobiasGoerke I'll check what's the best option to do, to ultimately get rid of fixed `ijson` version.  I've created a [ticket](https://issues.hibernatingrhinos.com/issue/RDBC-718/Revert-fixed-ijson-version-and-update-it-to-the-current-one) on the bug tracker.

**Comment by TobiasGoerke** [comment]
> @TobiasGoerke I'll check what's the best option to do, to ultimately get rid of fixed `ijson` version. I've created a [ticket](https://issues.hibernatingrhinos.com/issue/RDBC-718/Revert-fixed-ijson-version-and-update-it-to-the-current-one) on the bug tracker.

Thanks!
The package is only used in one file:
image

We have already refactored the module to work with newer ijson versions in our build and will create a PR next week, if you like.

**Comment by poissoncorp** [comment]
If you'd like to make a contribution, pull requests are welcome :)
Feel free to submit your changes, and I'll make sure to link them to this issue.

**Pull request merged**
